spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userbookss?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: roota
    password: roota

upload:
  dir: /Users/karen/data/lessons/java2021/

