spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userbook?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2021JavaForTest@gmail.com
    password: forTest2021
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true


logging:
  file:
    path: /Users/karen/data/lessons/java2021/spring/SpringDemo/log/
    name: springdemo.log

upload:
  dir: /Users/karen/data/lessons/java2021/spring/SpringDemo/upload

site:
  url: http://localhost:8080